<a href="https://colab.research.google.com/github/sjsjcheon/cbe4100lab1/blob/main/HeatDataAnalysisLAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Analysis of a Douple Pipe Heat Exchanger
authors: Saejoon Cheon, Kofi Nightingale, Jake Reisner, Guillermo Ribeiro

CBE 410

Prof. Huff, Prof. Lu

September 8 2022

#Dimensions


In the following diagram of the concentric heat exchanger from the lab sheet, 

---

it is clear which dimensions are needed in order to perform calculations relevant to the heat transfer analysis of this heat exchanger.


![pipe cross-section](https://github.com/gui11erv/CBE410/blob/main/Heat%20Data%20Analysis/images/cross-section.png?raw=true)


The necessary dimensions are the inner ($D_{1,i}$) and outer ($D_{1,o}$) diameters of the interior tube (hot water), and the inner ($D_{2,i}$) and outer ($D_{2,o}$) diameters of the annulus (cold water). It will also be necessary to know the total length ($L$) of the heat exchanger in order to calculate the necessary surface areas for heat transfer: $A_s = PL$ where $P$ is the perimeter of a cross-section of a tube:

$A_{s,i} = P_iL = {\pi}D_{1,i}L$ for the heat transfer surface area of the hot (inner) fluid

$A_{s,o} = P_oL = {\pi}D_{1,o}L$ for the heat transfer surface area of the cold (outer) fluid

Other necessary dimensions are the cross-sectional areas of fluid flow in the tubes, which are directly related to the tube diameters:

$A_{interior}=\frac{{\pi}D_{1,i}^2}{4}$ for the interior tube 

$A_{annulus}=\frac{{\pi}(D_{2,i}^2-D_{1,o}^2)}{4}$ for the annulus

And the hydraulic diameters of the inner tube and the outer annulus, necessary for calculations of dimensionless Reynolds and Nusselt numbers, given by $D_H = \frac{4A}{P}$:

$D_{H,interior} = \frac{4A_{interior}}{P_{interior}} = D_{1,i}$

$D_{H,annulus} = \frac{4A_{annulus}}{P_{annulus}} = 4\frac{\frac{{\pi}(D_{2,i}^2-D_{1,o}^2)}{4}}{{\pi}(D_{2,i}+D_{1,o})}=D_{2,i}-D_{1,o}$

The following table contains all of the dimensions that are used in the calculations in the succeeding sections of the lab report:

Dimension  | Value 
-------------------|------------------
Interior Pipe Inner Diameter, $D_{1,i}=D_{H,interior}$      | $16 mm = .016 m$ 
Interior Pipe Outer Diameter, $D_{1,o}$       | $18 mm = .018 m$
Interior Pipe Cross-Sectional Area, $A_{interior}$       | $64{\pi}mm^2=.000064{\pi}m^2$
Annulus Inner Diameter, $D_{2,i}$       | $26 mm = .026 m$
Annulus Outer Diameter, $D_{2,o}$       | $28 mm = .028 m$
Annulus Cross-Sectional Area, $A_{annulus}$       | $88{\pi}mm^2=.000088{\pi}m^2$
Annulus Hydraulic Diameter, $D_{H,annulus}$       | $8 mm = .008 m$ 
Heat Exchanger Length, $L$       | $1000 mm = 1 m$
Heat Exchanger Inner Wall Surface Area, $A_{s,i}$       | $16000{\pi} mm^2 = .016{\pi} m^2$
Heat Exchanger Outer Wall Surface Area, $A_{s,o}$       | $18000{\pi} mm^2 = .018{\pi} m^2$




In [ ]:
## the above data table stored as variables in python to be used for calculations
import numpy as np

d_1i = .016 # interior pipe inner diameter (meters). this is also the hydraulic diameter of the interior pipe
d_1o = .018 # interior pipe outer diameter (meters)

d_2i = .026 # annulus inner diameter (meters)
d_2o = .028 # annulus outer diameter (meters)

a_int = d_1i**2*np.pi/4 # interior pipe cross-sectional area (square meters)
a_ann = (d_2i**2-d_1o**2)*np.pi/4 # annulus cross-sectional area (square meters)

d_h = d_2i-d_1o # hydraulic diameter of annulus (meters)

L = 1 # heat exchanger length (meters)

a_si = L*d_1i*np.pi # heat transfer surface area for hot (inner) fluid (square meters)
a_so = L*d_1o*np.pi # heat transfer surface area for cold (outer) fluid (square meters)


#Properties

In [ ]:
from re import T
import numpy as np
import matplotlib.pyplot as plt
from numpy import mean
! git clone https://github.com/sjsjcheon/cbe4100lab1

# Physical properties of tube in W/m*K
k_wall = 15

# Physical properties of fluid (hot or cold)

# Importing Table H-2 in same order for rows and columns
temp_data = np.loadtxt('cbe4100lab1/lab1data.txt').reshape(4,6)
print(temp_data)

# (average) temperatures
t_hot = np.array(temp_data[:,1:3]) #average hot water flow temperatures
t_film_hot = mean(t_hot,axis=1) 


t_cold = np.array(temp_data[:,4:6]) #average cold water flow temperatures
t_film_cold = mean(t_cold,axis=1)

# Heat capacity of fluid in J/kg*K
cp_hot = [4180,4180,4180,4180]
cp_cold = [4190,4190,4190,4190]

# Fluid density in kg/m^3
p_hot = [988,989,989,989]
p_cold = [999,999,999,1000]

# Volumetric flow rates in m^3/s
v_hot = 0.001*(1/60)*np.array(temp_data[:,0])
v_cold = 0.001*(1/60)*np.array(temp_data[:,3])

# Average velocity in m/s
u_hot = v_hot / a_int
u_cold = v_cold / a_ann

# Fluid dynamic viscosity in kg/m*s
mu_hot = 0.000001*np.array([552,560,566,573]) 
mu_cold = 0.000001*np.array([1110,1170,1220,1250])

# Thermal conductivity of the fluid in W/m*K
kf_hot = [0.643,0.642,0.641,0.640]
kf_cold = [0.591,0.588,0.585,0.583]


fatal: destination path 'cbe4100lab1' already exists and is not an empty directory.
[[ 1.9 53.4 45.4  1.   8.1 23.9]
 [ 1.9 53.1 44.1  1.5  7.8 20.2]
 [ 2.  52.6 43.3  2.   7.5 17.6]
 [ 1.9 52.2 42.3  2.4  7.4 15.8]]


To account for the temperature dependence of the physical properties, a different calculation was made for each design condition. Specifically, the film temperature (average of the inlet and outlet temperatures) was used when looking up physical properties for each of the four design conditions.

#Experimental

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from tabulate import tabulate

In [ ]:

hot_flow_heat = np.multiply(np.multiply(np.multiply(p_hot,v_hot),cp_hot),np.subtract(temp_data[:,1],temp_data[:,2])) #calculate heat lost by hot flow
cold_flow_heat = np.multiply(np.multiply(np.multiply(p_cold,v_cold),cp_cold),np.subtract(temp_data[:,5],temp_data[:,4])) #calculate heat gained by cold flow
heat_lost = np.subtract(hot_flow_heat, cold_flow_heat) #heat lost to surroundings

#print(hot_flow_heat) #uncomment to see hot flow heat lost
#print(cold_flow_heat) #uncomment to see cold flow heat gained
#print(heat_lost) #uncomment to see system heat lost



In [ ]:

#Calculate the log mean temperature difference of the system: 
d_temp_left = np.subtract(temp_data[:,2],temp_data[:,4])
d_temp_right = np.subtract(temp_data[:,1],temp_data[:,5])
log_mean_temp = np.divide(np.subtract(d_temp_left,d_temp_right),np.log(np.divide(d_temp_left,d_temp_right))) 

print(log_mean_temp)

#Calculate the overall heat transfer coefficient (U):
u_exp_hot = np.divide(hot_flow_heat,np.multiply(log_mean_temp,0.016*np.pi)) #calculate U using the heat lost in the hot fluid
u_exp_cold = np.divide(cold_flow_heat,np.multiply(log_mean_temp,0.018*np.pi)) #calculate U using the heat gained in the cold fluid

print(u_exp_hot)
print(u_exp_cold)

[33.24764771 34.57214005 35.39849336 35.64473991]
[626.02947949 677.98691848 720.24397505 723.34388276]
[586.27590514 663.73170525 703.9997009  698.45024239]


In [ ]:
dc = ['Condition 1','Condition 2','Condition 3','Condition 4']
heat_headers = ['Design Conditions','Hot Flow Heat Lost \n(W)','Cold Flow Heat Gained \n(W)','Heat Lost By Surroundings\n(absorbed by heat exchanger) \n(W)'\
                ,'Log Mean Temperature Difference \n(K)','Experimental U \n(Hot Fluid) \n(W/m2K)','Experimental U \n(Cold Fluid) \n(W/m2K)']

heat_table = tabulate(np.transpose([dc,hot_flow_heat,cold_flow_heat,heat_lost,log_mean_temp, u_exp_hot,u_exp_cold]),headers= heat_headers,numalign='center')

print(heat_table)

temp_headers = ['Design Conditions','Hot Flow Rate (LPM)','Hot Temp In (C)','Hot Temp Out (C)','Cold Flow Rate (LPM)','Cold Temp In (C)','Cold Temp Out (C)']
temp_table = tabulate(np.append(np.array(dc).reshape(4,1),temp_data,axis=1),headers=temp_headers,numalign='center')

print('\n'+temp_table)

Design Conditions     Hot Flow Heat Lost     Cold Flow Heat Gained       Heat Lost By Surroundings      Log Mean Temperature Difference     Experimental U     Experimental U
                              (W)                     (W)              (absorbed by heat exchanger)                   (K)                    (Hot Fluid)        (Cold Fluid)
                                                                                    (W)                                                         (W/m2K)            (W/m2K)
-------------------  ---------------------  ------------------------  -------------------------------  ----------------------------------  -----------------  -----------------
Condition 1                 1046.23                 1102.26                       56.0372                           33.2476                     626.029            586.276
Condition 2                 1178.2                   1297.6                       119.405                           34.5721            

Design Conditions      Hot Flow Rate (LPM)    Hot Temp In (C)    Hot Temp Out (C)    Cold Flow Rate (LPM)    Cold Temp In (C)    Cold Temp Out (C)
-------------------  ---------------------  -----------------  ------------------  ----------------------  ------------------  -------------------
Condition 1                            1.9               53.4                45.4                     1                   8.1                 23.9
Condition 2                            1.9               53.1                44.1                     1.5                 7.8                 20.2
Condition 3                            2                 52.6                43.3                     2                   7.5                 17.6
Condition 4                            1.9               52.2                42.3                     2.4                 7.4                 15.8


What impacts the magnitude of the heat lost by the 
system?

In this case, the system actually gains heat, because the surrounding environment is hotter than the cold fluid. The primary contributor to heat lost to the system is the difference in temperature between the cold fluid and the surroundings (room temperature). As the exit temperature of the cold fluid decreases, so does the average temperature of the cold fluid in the heat exchanger, and therefore the heat transfer from the surroundings to the heat exchanger increases. This is evident in the data table above.

Since there is little/no insulation between the system and the surroundings the magnitude of the heat transfer will be larger.

#Correlations

## Hot Fluid

In [ ]:
## Hot Fluid, Reynolds number

re_hot = p_hot*u_hot*d_1i/mu_hot
print("Re: " , re_hot)

In [ ]:
## Hot Fluid, Prandtl number

pr_hot = mu_hot*cp_hot/kf_hot

## Cold Fluid

In [ ]:
## Cold Fluid, Reynolds number

re_cold = p_cold*u_cold*d_h/mu_cold
print("Re: ", re_cold)

In [ ]:
## Cold Fluid, Prandtl number

pr_cold = mu_cold*cp_cold/kf_cold
print("Pr: ", pr_cold)

The flows are turbulent in all four cases for the hot fluid, and the flows are laminar in all four cases for the cold fluid.

**Hydrodynamic Considerations**
> Inner Tube: Assume turbulent flow if Re >= 2300. Onset of fully developed flow for turbulent flow occurs at (x/D) > 10. This x value represents the hydrodynamic entry length. Heat and mass transfer textbook pg. 417

> Annulus: X = 0.05*Re*D_h where D_h represents hydraulic diameter

**Thermal Considerations**
> Inner Tube: For turbulent flow, x/D = 10. Textbook p 476

> Annulus: Laminar. X = 0.05*Re*Pr*D_h where D_h represents hydraulic diameter

In [ ]:
#Hydrodynamic entry lengths for all four cases for the hot fluid

l_hyd_turb_hot = 10*d_1i
print("Hyd entry length: ", l_hyd_turb_hot, "m")

#Thermal entry lengths for all four cases for the hot fluid
l_therm_turb_hot = 10*d_1i
print("Thermal entry length: ", l_therm_turb_hot, "m")

In [ ]:
#Hydrodynamic entry lengths for all four cases for the cold fluid

l_hyd_lam_cold = 0.05*re_cold*d_h
print("Hyd entry length: ", l_hyd_lam_cold, "m")

#Thermal entry lengths for all four cases for the cold fluid
l_therm_lam_cold = 0.05*re_cold*pr_cold*d_h
print("Thermal entry length: ", l_therm_lam_cold, "m")

Hot Fluid Nusselt Correlation. From Heat and Mass Transfer book p. 519, equations 8.21 and 8.62. Turbulent and fully developed.

In [ ]:
# Hot Fluid

friction_factors = (0.790*np.log(re_hot)-1.64)**-2
print("Friction factors: ", friction_factors)

nu_hot = (friction_factors/8)*(re_hot-1000)*pr_hot/(1+12.7*((friction_factors/8)**0.5)*(pr_hot**(2/3)-1))
print("Nusselt numbers: ", nu_hot)

Cold Fluid Nusselt Correlation. From H&M book p. 519, equation 8.58. x represents total length per Prof. Lu. Laminar and combined entry length.

In [ ]:
graetz = (d_h/L)*re_cold*pr_cold
nu_cold_numerator_term_1 = 3.66/np.tanh(2.264*graetz**(-1/3)+1.7*graetz**(-2/3))
nu_cold_numerator_term_2 = 0.0499*graetz*np.tanh(graetz**-1)
nu_cold_denominator = np.tanh(2.432*(pr_cold**(1/6))*(graetz**(-1/6)))
nu_cold = (nu_cold_numerator_term_1 + nu_cold_numerator_term_2)/nu_cold_denominator
print("Nusselt Numbers: ", nu_cold)

In [ ]:
# Resistances to heat transfer

# Outer (shell) side
ho = nu_cold*kf_cold/d_h
R_h = 1/(ho*a_so)

# Through the wall
R_w = (np.log((d_1o/d_1i)))/(2*np.pi*k_wall*L)

# Inner (tube) side
hi = nu_hot*kf_hot/d_1i
R_i = 1/(hi*a_si)
print(R_i)
# Theoretical overall heat transfer coefficient, UA in W/K
UA = (R_h + R_w + R_i)**(-1)
print ("Theoretical Overall Heat Transfer Coefficient UA = ", UA, "Watts/K")

## suppose A is the average of the heat transfer surface areas, a_si and a_so
A = .5*(a_si+a_so)
# calculate U as UA/A (approximation)
U = UA/A
print ("Theoretical Overall Heat Transfer Coefficient U = ", U, "Watts/m^2K")

The heat transfer efficiency would be improved by thickening the insulation around the outer tube to reduce heat lost from the outer tube to the surroundings.


#Results


In [ ]:
def u_calc(Pr,Re):
  d_h = 0.008
  graetz = (d_h/1)*Re*Pr
  nu_cold_numerator_term_1 = 3.66/np.tanh(2.264*graetz**(-1/3)+1.7*graetz**(-2/3))
  nu_cold_numerator_term_2 = 0.0499*graetz*np.tanh(graetz**-1)
  nu_cold_denominator = np.tanh(2.432*(Pr**(1/6))*(graetz**(-1/6)))
  nu_cold = (nu_cold_numerator_term_1 + nu_cold_numerator_term_2)/nu_cold_denominator

  k_cold = np.mean(kf_cold)
  D_cold = d_h
  a_cold = a_so

  h_cold = k_cold*nu_cold/D_cold
  R_cold = 1/(h_cold*a_cold)

  R_wall = R_w
  R_hot = np.mean(R_i)

  a = A
  u = ((R_hot + R_wall + R_cold)**(-1))/a
  return u

re_cold_smooth = np.linspace(350,1100,100)
u_smooth = u_calc(np.mean(pr_cold),re_cold_smooth)
print(u_calc(np.mean(pr_cold),re_cold))



In [ ]:
plt.plot(re_cold,u_exp_cold,'o')
plt.plot(re_cold_smooth,u_smooth,'orange')
plt.xlim([200,1200])
plt.ylim([0,1000])
plt.title("Overall Heat Transfer Coefficient vs Reynolds Number of the Cold (outer) Fluid",fontweight='bold')
plt.xlabel("Reynolds Number of Cold Fluid")
plt.ylabel("Overall Heat Transfer Coefficient U (W/m^2K)")
plt.legend(['experimental calculations','theoretical correlations'])